unit ws_login;

//  *************************************************
//    Generated By: JsonToDelphiClass - 0.65
//    Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
//    Generated On: 2022-11-11 16:07:05
//  *************************************************
//    Created By  : Petar Georgiev - 2014
//    WebSite     : http://pgeorgiev.com
//  *************************************************

interface

uses Generics.Collections, Rest.Json;

type

TRESULTClass = class
private
  FRetCodigo: Integer;
  FRetMensagem: String;
  FGusr_acessos: String;
  FGusr_codigo: Integer;
  FGusr_nome: String;
  FGusr_senha: String;
public
  property RetCodigo: Integer read FRetCodigo write FRetCodigo;
  property RetMensagem: String read FRetMensagem write FRetMensagem;
  property gusr_acessos: String read FGusr_acessos write FGusr_acessos;
  property gusr_codigo: Integer read FGusr_codigo write FGusr_codigo;
  property gusr_nome: String read FGusr_nome write FGusr_nome;
  property gusr_senha: String read FGusr_senha write FGusr_senha;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TRESULTClass;
end;

TRootClass = class
private
  FRESULT: TRESULTClass;
public
  property RESULT: TRESULTClass read FRESULT write FRESULT;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TRootClass;
end;

implementation

{TRESULTClass}


function TRESULTClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TRESULTClass.FromJsonString(AJsonString: string): TRESULTClass;
begin
  result := TJson.JsonToObject<TRESULTClass>(AJsonString)
end;

{TRootClass}

constructor TRootClass.Create;
begin
  inherited;
  FRESULT := TRESULTClass.Create();
end;

destructor TRootClass.Destroy;
begin
  FRESULT.free;
  inherited;
end;

function TRootClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TRootClass.FromJsonString(AJsonString: string): TRootClass;
begin
  result := TJson.JsonToObject<TRootClass>(AJsonString)
end;

end.

