unit ws_SincProd;

//  *************************************************
//    Generated By: JsonToDelphiClass - 0.65
//    Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
//    Generated On: 2022-11-22 23:40:40
//  *************************************************
//    Created By  : Petar Georgiev - 2014
//    WebSite     : http://pgeorgiev.com
//  *************************************************

interface

uses Generics.Collections, Rest.Json;

type

TProdutosClass = class
private
  FGs_Ativo: String;
  FGs_Bloqueado: String;
  FGs_CodBarras: String;
  FGs_Complemento: String;
  FGs_DataFinOf: String;
  FGs_DataIniOF: String;
  FGs_DataPrVenda: String;
  FGs_Descsricao: String;
  FGs_DptoCodigo: String;
  FGs_DptoDescricao: String;
  FGs_Estoque1: Extended;
  FGs_Estoque2: Extended;
  FGs_Estoque3: Extended;
  FGs_Estoque4: Extended;
  FGs_Estoque5: Extended;
  FGs_FatorEst3: Extended;
  FGs_GrupoCodgigo: String;
  FGs_GrupoDescricao: String;
  FGs_Marca: String;
  FGs_Oferta: String;
  FGs_PrNormal: Extended;
  FGs_PrVenda: Extended;
  FGs_PrVenda3: Extended;
  FGs_Unidade: String;
  FGs_codigo: integer;
  FGs_vdonline: Extended;
public
  property gs_Ativo: String read FGs_Ativo write FGs_Ativo;
  property gs_Bloqueado: String read FGs_Bloqueado write FGs_Bloqueado;
  property gs_CodBarras: String read FGs_CodBarras write FGs_CodBarras;
  property gs_Complemento: String read FGs_Complemento write FGs_Complemento;
  property gs_DataFinOf: String read FGs_DataFinOf write FGs_DataFinOf;
  property gs_DataIniOF: String read FGs_DataIniOF write FGs_DataIniOF;
  property gs_DataPrVenda: String read FGs_DataPrVenda write FGs_DataPrVenda;
  property gs_Descsricao: String read FGs_Descsricao write FGs_Descsricao;
  property gs_DptoCodigo: String read FGs_DptoCodigo write FGs_DptoCodigo;
  property gs_DptoDescricao: String read FGs_DptoDescricao write FGs_DptoDescricao;
  property gs_Estoque1: Extended read FGs_Estoque1 write FGs_Estoque1;
  property gs_Estoque2: Extended read FGs_Estoque2 write FGs_Estoque2;
  property gs_Estoque3: Extended read FGs_Estoque3 write FGs_Estoque3;
  property gs_Estoque4: Extended read FGs_Estoque4 write FGs_Estoque4;
  property gs_Estoque5: Extended read FGs_Estoque5 write FGs_Estoque5;
  property gs_FatorEst3: Extended read FGs_FatorEst3 write FGs_FatorEst3;
  property gs_GrupoCodgigo: String read FGs_GrupoCodgigo write FGs_GrupoCodgigo;
  property gs_GrupoDescricao: String read FGs_GrupoDescricao write FGs_GrupoDescricao;
  property gs_Marca: String read FGs_Marca write FGs_Marca;
  property gs_Oferta: String read FGs_Oferta write FGs_Oferta;
  property gs_PrNormal: Extended read FGs_PrNormal write FGs_PrNormal;
  property gs_PrVenda: Extended read FGs_PrVenda write FGs_PrVenda;
  property gs_PrVenda3: Extended read FGs_PrVenda3 write FGs_PrVenda3;
  property gs_Unidade: String read FGs_Unidade write FGs_Unidade;
  property gs_codigo: integer read FGs_codigo write FGs_codigo;
  property gs_vdonline: Extended read FGs_vdonline write FGs_vdonline;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TProdutosClass;
end;

TRESULTClass = class
private
  FProdutos: TArray<TProdutosClass>;
  FRetCodigo: integer;
  FRetMensagem: String;
public
  property Produtos: TArray<TProdutosClass> read FProdutos write FProdutos;
  property RetCodigo: integer read FRetCodigo write FRetCodigo;
  property RetMensagem: String read FRetMensagem write FRetMensagem;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TRESULTClass;
end;

TRootClass = class
private
  FRESULT: TRESULTClass;
public
  property RESULT: TRESULTClass read FRESULT write FRESULT;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TRootClass;
end;

implementation

{TProdutosClass}


function TProdutosClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TProdutosClass.FromJsonString(AJsonString: string): TProdutosClass;
begin
  result := TJson.JsonToObject<TProdutosClass>(AJsonString)
end;

{TRESULTClass}

destructor TRESULTClass.Destroy;
var
  LProdutosItem: TProdutosClass;
begin

 for LProdutosItem in FProdutos do
   LProdutosItem.free;

  inherited;
end;

function TRESULTClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TRESULTClass.FromJsonString(AJsonString: string): TRESULTClass;
begin
  result := TJson.JsonToObject<TRESULTClass>(AJsonString)
end;

{TRootClass}

constructor TRootClass.Create;
begin
  inherited;
  FRESULT := TRESULTClass.Create();
end;

destructor TRootClass.Destroy;
begin
  FRESULT.free;
  inherited;
end;

function TRootClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TRootClass.FromJsonString(AJsonString: string): TRootClass;
begin
  result := TJson.JsonToObject<TRootClass>(AJsonString)
end;

end.

